format = """
$cmd_duration\n\
[  ](bg:#e2e2e3 fg:#1793d0)\
[](bg:#769ff0 fg:#e2e2e3)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_commit\
$git_state\
$git_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
[ ](fg:#212736)\
"""
# \n$character"""

add_newline = false

[directory]
style = "fg:#e2e2e3 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[package]
disabled = true
style = "bg:#394260"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
style = "bg:#212736"
# format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
format = '[[ $symbol](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "🦀"
style = "bg:#212736"
format = '[[ $symbol](fg:#769ff0 bg:#212736)]($style)'

[golang]
style = "bg:#212736"
format = '[[ $symbol](fg:#769ff0 bg:#212736)]($style)'

[lua]
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
style = "bg:#212736"
format = '[[ $symbol($version) ($virtualenv) ](fg:#769ff0 bg:#212736)]($style)'

[c]
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[haskell]
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[dotnet]
style = "bg:#212736"
format = '[[ $symbol($version )(🎯 $tfm ) ](fg:#769ff0 bg:#212736)]($style)'

[php]
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[cmd_duration]
disabled = false

[time]
disabled = true 
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
